### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by ReedCopsey** [delegateas/delegateas.github.io#1]
I wanted to suggest updating your project logos to use the new F# Software Foundation logo for F#.

You can download the template from http://fsharp.org/foundation/logo.html

This composes nicely, and is more "obvious" than the "#" sign used previously in many F# related projects.  For example, see: http://fsprojects.github.io/FSharp.Data.HiveProvider/

**Comment by ghost** [comment]
Thx, we will update our logos:

http://delegateas.github.io/

as soon as possible :-)

## 

Regards / Atentamente / Mvh / Cordiali saluti

Ramón Salvador Soto Mathiesen
- Managing Specialist | CTO of CRM Department @ Delegate
- MSc Computer Science (Minor in Mathematics)
- Blog: http://blog.stermon.com/
